# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
description: Željko Filipin's blog.
email: zeljko.filipin@gmail.com
github_username:  zeljkofilipin
permalink: /:title
title: Filipin dot eu
twitter_username: zeljkofilipin
url: "http://filipin.eu/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
