# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Filipin.eu
email: zeljko.filipin@gmail.com
description: Željko Filipin's blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filipin.eu/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# Custom settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:title

# Minima https://github.com/jekyll/minima
theme: minima

## Social
twitter_username: zeljkofilipin
github_username:  zeljkofilipin
facebook_username: zeljko.filipin
linkedin_username: zeljkofilipin
youtube_username: zeljkofilipin
rss: rss

## Disqus
disqus:
  shortname: filipineu

## Google
google_analytics: UA-200958-28
