# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
description: Željko Filipin's blog.
email: zeljko.filipin@gmail.com
github_username:  zeljkofilipin
google_analytics: UA-200958-28
permalink: /:title
theme: minima
title: Filipin dot eu
twitter_username: zeljkofilipin
url: "http://filipin.eu/" # the base hostname & protocol for your site

# Build settings
# incremental: true
markdown: kramdown
